@ModelBindingFromBody_HostAddress = http://localhost:5217

GET {{ModelBindingFromBody_HostAddress}}/weatherforecast/
Accept: application/json

[
    {
        "id": 100,
        "name": "Laptop",
        "quantity": 10,
        "price": 2500
    },
    {
        "id": 101,
        "name": "Desktop",
        "quantity": 15,
        "price": 2900
    }
]

###
