// <auto-generated />
using System;
using MagicVilla.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240325023810_addUserToDb")]
    partial class addUserToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla.Models.LocalUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LocalUsers");
                });

            modelBuilder.Entity("MagicVilla.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "Private pool, Jacuzzi, BBQ area",
                            CreatedDate = new DateTime(2024, 3, 25, 9, 38, 10, 550, DateTimeKind.Local).AddTicks(7546),
                            Details = "A luxurious villa with breathtaking views.",
                            ImageUrl = "https://example.com/luxury-villa-image1.jpg",
                            Name = "Luxury Retreat Villa",
                            Occupancy = 8,
                            Rate = 500.0,
                            Sqft = 3500,
                            UpdatedDate = new DateTime(2024, 3, 25, 9, 38, 10, 550, DateTimeKind.Local).AddTicks(7555)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Direct beach access, Outdoor dining area",
                            CreatedDate = new DateTime(2024, 3, 25, 9, 38, 10, 550, DateTimeKind.Local).AddTicks(7558),
                            Details = "Experience tranquility by the sea in this beautiful villa.",
                            ImageUrl = "https://example.com/seaside-villa-image1.jpg",
                            Name = "Seaside Serenity Villa",
                            Occupancy = 6,
                            Rate = 400.0,
                            Sqft = 2800,
                            UpdatedDate = new DateTime(2024, 3, 25, 9, 38, 10, 550, DateTimeKind.Local).AddTicks(7558)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "Fireplace, Hiking trails nearby",
                            CreatedDate = new DateTime(2024, 3, 25, 9, 38, 10, 550, DateTimeKind.Local).AddTicks(7560),
                            Details = "Escape to the mountains in this cozy villa surrounded by nature.",
                            ImageUrl = "https://example.com/mountain-villa-image1.jpg",
                            Name = "Mountain Escape Villa",
                            Occupancy = 4,
                            Rate = 300.0,
                            Sqft = 2000,
                            UpdatedDate = new DateTime(2024, 3, 25, 9, 38, 10, 550, DateTimeKind.Local).AddTicks(7560)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "Garden, Outdoor seating area",
                            CreatedDate = new DateTime(2024, 3, 25, 9, 38, 10, 550, DateTimeKind.Local).AddTicks(7561),
                            Details = "Experience rustic charm in this countryside villa.",
                            ImageUrl = "https://example.com/rustic-villa-image1.jpg",
                            Name = "Rustic Charm Villa",
                            Occupancy = 5,
                            Rate = 250.0,
                            Sqft = 1800,
                            UpdatedDate = new DateTime(2024, 3, 25, 9, 38, 10, 550, DateTimeKind.Local).AddTicks(7562)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "Rooftop terrace, Gym facilities",
                            CreatedDate = new DateTime(2024, 3, 25, 9, 38, 10, 550, DateTimeKind.Local).AddTicks(7563),
                            Details = "An oasis in the heart of the city, offering luxury and convenience.",
                            ImageUrl = "https://example.com/urban-villa-image1.jpg",
                            Name = "Urban Oasis Villa",
                            Occupancy = 7,
                            Rate = 600.0,
                            Sqft = 3200,
                            UpdatedDate = new DateTime(2024, 3, 25, 9, 38, 10, 550, DateTimeKind.Local).AddTicks(7563)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
